### ISSUE TITLE
Unsupported file format: !C-l

### ISSUE THREAD

**Issue by troudki** [simondotm/ym2149f#18]
Hi Simon,

I tried to use your tool to convert a ym music that we currently use in a game remake.

`./ym2sn.py Return_to_Genesis1.ym
  ENV: set shape 0 hold=True [31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Parsing YM file...
YM Format: !C-l
Traceback (most recent call last):
  File "./ym2sn.py", line 2164, in <module>
    main()
  File "./ym2sn.py", line 2123, in main
    ym = YmReader(fd)
  File "./ym2sn.py", line 617, in __init__
    self.__parse_header()
  File "./ym2sn.py", line 680, in __parse_header
    raise Exception('Unsupported file format: ' + ym_format)
Exception: Unsupported file format: !C-l
`
Have we forgotten something ?
Bravo ! for this great tool

[Return_to_Genesis1.ym.zip](https://github.com/simondotm/ym2149f/files/2946599/Return_to_Genesis1.ym.zip)

Our remake 
http://www.z-team.fr/return2genesis.html

**Comment by simondotm** [comment]
Hello there!
Yes, I should add this to the readme, but the script at present will not open raw YM files. 

What I mean by "raw YM" is that YM files are in fact LHA archive files that contain the "actual" YM file within them. So if you have something like 7zip installed, open up your YM file with that, to reveal the inner YM file, extract that, and feed that to the script instead.

Its fiddly I know, but unfortunately LHA files are a bit tricky to support in Python so this is the only workaround I have at the moment!

Here's the converted VGM:
[genesis1.zip](https://github.com/simondotm/ym2149f/files/2969036/genesis1.zip)

Best,
Simon

**Comment by simondotm** [comment]
By the way your project looks very cool. Out of interest what sound chip are you wanting to get this music running on?

**Comment by simondotm** [comment]
I've just updated the script to have a better command line parser. It now reports a more helpful error if the YM file fed to it is the LHA archive rather than the inner YM binary.

**Comment by troudki** [comment]
Thx Simon, your tool is perfect for SN76489 Chip on Sega Megadrive.. https://segaretro.org/SN76489
 We will put your name in credits list in the next remake ;-)

**Comment by simondotm** [comment]
No worries, glad you found it useful! I knew there was an SN in the Sega Master System, but I didn't know until now that there was one in the Megadrive too!
Let me know how you get on. 
Best
Simon

**Comment by simondotm** [comment]
BTW if the megadrive sound chip is similar to the master system, it has a LFSR tap on bit 16 for periodic noise, so that define in the script probably needs modifying for your music.

**Comment by troudki** [comment]
Hi Simon, I tried for a new remake in progress..I have messages below
WARNING: Noise tone 0 - should not happen!
ERROR: Noise is enabled at frequency 0 - unexpected
[BVOLLEY1.BIN.zip](https://github.com/simondotm/ym2149f/files/3025476/BVOLLEY1.BIN.zip)
